repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-added-large-files
        args: [--maxkb=5000]
      - id: check-merge-conflict
      - id: check-toml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.2.4
    hooks:
      - id: sqlfluff-lint
        name: sqlfluff-lint
        stages: [manual]
        additional_dependencies:
          - sqlfluff-templater-dbt==3.2.4
          - dbt-core==1.8.4
          - dbt-duckdb==1.8.1
        args: [--dialect=duckdb]
